### ISSUE TITLE
Lint & Authentication errors[Need Help]

### ISSUE THREAD

**Issue by keronei** [dhis2/dhis2-android-sdk#1288]
I have included this SDK via gradle to my android project, during gradle build, I get a bunch of lint errors including ```java  Method 'getRequestedCoordinates' is not used by the IDE```  and _error: string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'_.

I have somehow managed to get the app running but I don't seem to go past the login screen. When I input the server and credentials, It loads for a while then returns 'failed', on the stack trace, here's what I have collected.

 2020-06-07 08:23:42.387 6259-6335/com.keronei.notifierclinet E/APIErrorMapper: okhttp3.ResponseBody$1@7e3aea4

```
2020-06-07 08:23:42.387 6259-6259/com.keronei.notifierclinet W/System.err: org.hisp.dhis.android.core.maintenance.AutoValue_D2Error
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.maintenance.$$AutoValue_D2Error$Builder.autoBuild($$AutoValue_D2Error.java:226)
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.maintenance.D2Error$Builder.build(D2Error.java:108)
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.arch.api.executors.internal.APIErrorMapper.responseException(APIErrorMapper.java:170)
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.arch.api.executors.internal.APICallExecutorImpl.executeObjectCallInternal(APICallExecutorImpl.java:118)
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.arch.api.executors.internal.APICallExecutorImpl.executeObjectCallWithErrorCatcher(APICallExecutorImpl.java:92)
2020-06-07 08:23:42.388 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.user.internal.UserAuthenticateCallFactory.loginInternal(UserAuthenticateCallFactory.java:138)
2020-06-07 08:23:42.389 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.user.internal.UserAuthenticateCallFactory.lambda$logIn$0$UserAuthenticateCallFactory(UserAuthenticateCallFactory.java:121)
2020-06-07 08:23:42.389 6259-6259/com.keronei.notifierclinet W/System.err:     at org.hisp.dhis.android.core.user.internal.-$$Lambda$UserAuthenticateCallFactory$L0YL_YnXIkuGYkj92qiEawmjwgU.subscribe(Unknown Source:8)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2020-06-07 08:23:42.390 6259-6259/com.keronei.notifierclinet W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-07 08:23:42.391 6259-6259/com.keronei.notifierclinet W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-06-07 08:23:42.391 6259-6259/com.keronei.notifierclinet W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-06-07 08:23:42.391 6259-6259/com.keronei.notifierclinet W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-06-07 08:23:42.391 6259-6259/com.keronei.notifierclinet W/System.err:     at java.lang.Thread.run(Thread.java:764)
```
I've been stuck here for quite some time, Please shed some light.

org.hisp.dhis:android-core:1.1.0

I have pulled some basic gradle configuration from the [dhis2-android-skeleton-app](https://github.com/dhis2/dhis2-android-skeleton-app) as well.

com.facebook.stetho:stetho:1.5.0
com.facebook.stetho:stetho-okhttp3:1.5.0

   ```groovy configurations.all {
        resolutionStrategy {
            force 'junit:junit:4.12','com.squareup.okhttp3:okhttp:3.12.0'
        }
```

Android Studio 3.6.1
Project compileSDK 19
buildToolsVersion 29.0.3
minSDKVersion 19
targetSDKVersion 29

I have pulled some basic gradle configuration from the [dhis2-android-skeleton-app](https://github.com/dhis2/dhis2-android-skeleton-app) as well.

**Comment by vgarciabnz** [comment]
Closed because it is been followed-up in the community https://community.dhis2.org/t/error-in-dhis2-android-skeleton-app-fresh-build/39441/5
