### ISSUE TITLE
Integrating SDK gives build errors  

### ISSUE THREAD

**Issue by apoorv9990** [dhis2/dhis2-android-sdk#50]
Hi, I am trying to integrate the SDK into an app. This is how my settings.gradle looks like
    
    include ':app', ':sdk', ':core', ':persistence', ':core-java', ':models'
    project(':sdk').projectDir = new File(settingsDir, '../dhis2-android-sdk-master/app')
    project(':core').projectDir = new File(settingsDir, '../dhis2-android-sdk-master/core')
    project(':persistence').projectDir = new File(settingsDir, '../dhis2-android-sdk-master/persistence')
    project(':core-java').projectDir = new File(settingsDir, '../dhis2-android-sdk-master/core-java')
    project(':models').projectDir = new File(settingsDir, '../dhis2-android-sdk-master/models')

My build.gradle for my app module looks like

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "emmunify.com.emmunify"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        // gradle requires to exclude these files both
        // with .txt extension and without.
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'

        // without .txt
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'

        // gradle requires to exclude these files both
        // with .txt extension and without.
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'

        // without .txt
        exclude 'META-INF/notice'
        exclude 'META-INF/license'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.parse.bolts:bolts-tasks:1.3.0'
    compile 'com.parse:parse-android:1.11.0'
    compile 'joda-time:joda-time:2.9.1'
    compile project(':sdk')
    compile project(':core')
    compile 'com.android.support:appcompat-v7:23.0.0'
}
```

and my build.gradle for my project looks like

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    // SDK version.
    versionCode = 1
    versionName = "1.0"

    // Compilation configuration.
    minSdkVersion = 15
    compileSdkVersion = 23
    targetSdkVersion = 23
    buildToolsVersion = "23.0.2"
}
```

Now when I try to run my app it gives me the following build error

```
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:752)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:672)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
	at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
	at com.android.dx.command.dexer.Main.processClass(Main.java:749)
	... 12 more
1 error; aborting
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1
```

Can somebody guide as to what I am doing wrong?

**Comment by simernes** [comment]
Hi @apoorv9990 
Which branch are you on? Can you please make sure you are on the refactoring branch?

**Comment by apoorv9990** [comment]
hi @simernes 
Thanks for the guidance. I was able to integrate it once I switched to the refactoring branch.
